#!/usr/bin/env bash

set -e
set -x

# Change to this script's own directory, then back up one level.
cd "$(dirname "$0")"
cd ..

if [ ! -f trackless_server.crt ]; then
  pushd ~/.ssh

  # All of this makes a self-signed certificate. You know what's hard to get modern browsers to use? A self-signed certificate.
  # See https://gist.github.com/tadast/9932075
  openssl genrsa -out trackless_server.orig.key 4096
  openssl rsa -in trackless_server.orig.key -out trackless_server.key
  #openssl req -new -key server.key -out server.csr
  openssl req -new -key trackless_server.key -x509 -nodes -new -out trackless_server.crt -subj /CN=localhost.ssl -reqexts SAN -extensions SAN -config <(cat /System/Library/OpenSSL/openssl.cnf <(printf '[SAN]\nsubjectAltName=DNS:localhost.ssl')) -sha256 -days 3650
  #openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
  grep localhost.ssl /private/etc/hosts || (echo "127.0.0.1 localhost.ssl" | sudo tee -a /private/etc/hosts)

  # openssl req -newkey rsa:4096 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
  popd
  cp ~/.ssh/trackless_server.* .
fi

#thin start -R config.ru -p 3002 --ssl --ssl-key-file ./trackless_server.key --ssl-cert-file ./trackless_server.crt &
#thin start -R config.ru -p 3001 &

# Thin doesn't seem to support HTTP and HTTPS on the same port (fair), but *does* support HTTPS and WSS on the same port.
thin start -R config.ru -p 3001 --ssl --ssl-disable-verify --ssl-key-file ./trackless_server.key --ssl-cert-file ./trackless_server.crt
#thin start -R config.ru -p 3001

# I'm having *no* luck getting Puma to work for this.
#puma -b 'ssl://127.0.0.1:3001?key=trackless_server.key&cert=trackless_server.crt'
#puma -b 'tcp://127.0.0.1:3001'
